import {
  Boxes,
  CalendarDays,
  Clock3,
  Factory,
  Gauge,
  Globe2,
  MessagesSquare,
  Network,
  PackageOpen,
  Route,
  ShieldCheck,
  Truck,
  Users,
  Warehouse,
} from "lucide-react";

export const iconMap = {
  truck: Truck,
  route: Route,
  boxes: Boxes,
  warehouse: Warehouse,
  weight: PackageOpen,
  users: Users,
  globe: Globe2,
  clock: Clock3,
  shield: ShieldCheck,
  calendar: CalendarDays,
  package: PackageOpen,
  factory: Factory,
  message: MessagesSquare,
  speed: Gauge,
  network: Network,
};
